/**
 * Reads the evidence package and writes `artifacts/evidence/summary.md`.
 *
 * Nothing here computes or estimates anything: every number is copied from a file the test suite
 * produced, and every row names the file it came from. If a record is missing the row says so rather
 * than guessing, which is what stops the report drifting away from what was actually measured.
 *
 *   node scripts/report.mjs
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const DIR = 'artifacts/evidence';

const read = (name) => {
  const p = join(DIR, name);
  if (!existsSync(p)) return null;
  try {
    return JSON.parse(readFileSync(p, 'utf8'));
  } catch {
    return null;
  }
};

const n = (v, digits = 1) => (typeof v === 'number' ? v.toFixed(digits) : '—');
const missing = (file) => `— _(${file} not present)_`;

const core = read('core-loop.json');
const startup = read('startup.json');
const risk = read('route-risk.json');
const esc = read('escalation.json');
const loss = read('scout-loss.json');
const win = read('run-win.json');
const lose = read('run-loss.json');
const reckless = read('run-reckless-mid.json');
const n1 = read('run-win-night1.json');
const n2 = read('run-win-night2.json');
const restarts = read('restarts.json');
const focus = read('focus-loss.json');
const perf = read('perf/perf.json');
const deploy = read('deployment.json');
const assets = read('asset-audit.json');

const lines = [];
const push = (s = '') => lines.push(s);

push('# Evidence summary');
push();
push('Generated by `node scripts/report.mjs` from the files the test suite produced. Every row names');
push('its source. Do not edit by hand.');
push();

push('## Pacing');
push();
push('| Metric | Budget | Measured | Source |');
push('| ------ | ------ | -------- | ------ |');
push(
  `| Cold load to playable | < 8 s | ${startup ? `${n(startup.loadMs / 1000, 2)} s` : missing('startup.json')} | \`startup.json\` |`,
);
push(
  `| Procedural asset build | — | ${startup?.startup ? `${n(startup.startup.atlasMs, 1)} ms` : '—'} | \`startup.json → startup.atlasMs\` |`,
);
push(
  `| First movement | ≤ 15 s | ${core ? `${n(core.firstMoveAt, 1)} s` : missing('core-loop.json')} | \`core-loop.json\` |`,
);
push(
  `| First pheromone trail | — | ${core ? `${n(core.firstTrailAt, 1)} s` : '—'} | \`core-loop.json\` |`,
);
push(
  `| First worker delivery | ≤ 60 s | ${core ? `${n(core.firstDeliveryAt, 1)} s` : '—'} | \`core-loop.json\` |`,
);
push(
  `| First crack claimed | ≤ 5 min | ${win?.stats ? `${n(win.stats.firstClaimAt, 1)} s` : missing('run-win.json')} | \`run-win.json → stats.firstClaimAt\` |`,
);
push(
  `| Winning run length | 12–15 min | ${win?.stats ? `${n(win.stats.runSeconds / 60, 1)} min` : '—'} | \`run-win.json → stats.runSeconds\` |`,
);
push(
  `| Idle seconds in the winning run | — | ${win?.stats ? `${n(win.stats.idleSeconds, 0)} s` : '—'} | \`run-win.json → stats.idleSeconds\` |`,
);
push(
  `| Restart to playable | ≤ 2 s | ${
    Array.isArray(restarts)
      ? `${n(Math.max(...restarts.map((r) => r.restartMs)) / 1000, 2)} s worst of 5`
      : missing('restarts.json')
  } | \`restarts.json\` |`,
);
push();

push('## Route choice');
push();
if (risk) {
  push('| Route | Mean exposure | Nodes | Source |');
  push('| ----- | ------------- | ----- | ------ |');
  push(
    `| Cover-hugging | ${n(risk.covered?.exposure, 3)} | ${risk.covered?.nodes ?? '—'} | \`route-risk.json\` |`,
  );
  push(
    `| Straight across open tile | ${n(risk.open?.exposure, 3)} | ${risk.open?.nodes ?? '—'} | \`route-risk.json\` |`,
  );
  const ratio =
    risk.covered?.exposure > 0 ? (risk.open.exposure / risk.covered.exposure).toFixed(2) : '—';
  push();
  push(`Open-floor routing carries **${ratio}×** the exposure of the covered route to the same node.`);
} else {
  push(missing('route-risk.json'));
}
push();

push('## Escalation and fairness');
push();
push('| Observation | Value | Source |');
push('| ----------- | ----- | ------ |');
if (esc) {
  push(`| Suspicion reached | ${n(esc.suspicion?.value, 1)} (tier ${esc.suspicion?.tier}) | \`escalation.json\` |`);
  push(`| Attributed last cause | \`${esc.suspicion?.lastCause}\` | \`escalation.json\` |`);
  push(`| Stated next response | ${esc.nextResponse} | \`escalation.json\` |`);
  push(
    `| Responses deployed | ${esc.counts?.patrols} patrol(s), ${esc.counts?.hazards} hazard(s) | \`escalation.json\` |`,
  );
  push(`| Scout deaths while loitering in light | ${esc.scoutDeaths} | \`escalation.json\` |`);
} else {
  push(`| — | ${missing('escalation.json')} | |`);
}
if (loss) {
  push(
    `| Colony size before/after a scout loss | ${loss.beforePop} → ${loss.afterPop} | \`scout-loss.json\` |`,
  );
}
if (reckless) {
  push(
    `| Reckless run peak suspicion | ${n(reckless.suspicion?.peak, 1)} | \`run-reckless-mid.json\` |`,
  );
}
push();

push('## Outcomes');
push();
push('| Run | Result | Colony | Suspicion peak | Source |');
push('| --- | ------ | ------ | -------------- | ------ |');
if (win) {
  push(
    `| Careful three-night run | **${win.status}** | ${win.colony?.population} roaches, ${Math.floor(win.colony?.food ?? 0)} food, ${Math.floor(win.colony?.water ?? 0)} moisture | ${n(win.suspicion?.peak, 1)} | \`run-win.json\` |`,
  );
} else {
  push(`| Careful three-night run | ${missing('run-win.json')} | | | |`);
}
if (lose) {
  push(
    `| Reckless run | **${lose.status}** (\`${lose.loseCause}\`) | ${lose.colony?.population} roaches | ${n(lose.suspicion?.peak, 1)} | \`run-loss.json\` |`,
  );
} else {
  push(`| Reckless run | ${missing('run-loss.json')} | | | |`);
}
push();
if (win?.winCriteria) {
  push('Win criteria at the end of the winning run:');
  push();
  for (const [k, v] of Object.entries(win.winCriteria)) push(`- ${v ? '✅' : '❌'} \`${k}\``);
  push();
}
if (n1 || n2) {
  push('Colony at each night boundary:');
  push();
  push('| Boundary | Time | Population | Food | Moisture | Source |');
  push('| -------- | ---- | ---------- | ---- | -------- | ------ |');
  if (n1)
    push(
      `| End of night 1 supply setup | ${n(n1.time, 0)} s | ${n1.colony?.population} | ${Math.floor(n1.colony?.food ?? 0)} | ${Math.floor(n1.colony?.water ?? 0)} | \`run-win-night1.json\` |`,
    );
  if (n2)
    push(
      `| Night 2, both cracks claimed | ${n(n2.time, 0)} s | ${n2.colony?.population} | ${Math.floor(n2.colony?.food ?? 0)} | ${Math.floor(n2.colony?.water ?? 0)} | \`run-win-night2.json\` |`,
    );
  push();
}

push('## Performance');
push();
if (perf) {
  push(
    `Reference: ${perf.reference?.viewport?.width}×${perf.reference?.viewport?.height} @ dpr ${perf.reference?.deviceScaleFactor}, ${perf.reference?.hardwareConcurrency} logical cores, headless Chromium.`,
  );
  push();
  push('| Window | Frames | p50 | p95 | p99 | worst | >50 ms | >100 ms | CPU p95 | Peak roaches | Peak hazards | Peak particles | Draw calls |');
  push('| ------ | ------ | --- | --- | --- | ----- | ------ | ------- | ------- | ------------ | ------------ | -------------- | ---------- |');
  const windows = [...(perf.windows ?? []), ...(win?.peakPerf ? [win.peakPerf] : [])].filter(Boolean);
  for (const w of windows) {
    push(
      `| ${w.label} | ${w.frames} | ${w.p50} | ${w.p95} | ${w.p99} | ${w.worst} | ${w.over50Pct}% | ${w.over100} | ${w.cpuP95 ?? '—'} | ${w.peak?.roaches} | ${w.peak?.hazards} | ${w.peak?.particles} | ${w.peak?.drawCalls} |`,
    );
  }
  push();
  push(
    `Fixed-clock health: ${perf.clock?.steps} steps, ${n(perf.clock?.discardedTime, 3)} s discarded, ${perf.clock?.overloadFrames} overload frame(s).`,
  );
  push(
    `Bundle: ${perf.bundle?.files} files, ${(perf.bundle?.bytes / 1024).toFixed(0)} kB on disk (sourcemap included), ${perf.bundle?.absoluteAssetRefs} absolute asset references.`,
  );
} else {
  push(missing('perf/perf.json'));
}
push();

push('## Static deployment');
push();
if (deploy) {
  push(`- Served from: \`${deploy.url}\``);
  push(`- Requests leaving the origin at runtime: **${deploy.externalRequests?.length ?? '—'}**`);
  push(`- Absolute asset references in \`dist/index.html\`: **${deploy.absoluteAssetRefs?.length ?? '—'}**`);
  push(`- \`.nojekyll\` present: **${deploy.nojekyll}**`);
  push(`- Files in \`dist/\`: ${(deploy.distFiles ?? []).join(', ')}`);
} else {
  push(missing('deployment.json'));
}
push();

push('## Assets');
push();
if (assets) {
  push(`- Temporary assets: **${(assets.temporaryAssets ?? []).length}**`);
  push(`- HUD icons rendered: ${assets.hudIcons}`);
  push(`- Peak audio voices during active play: ${assets.peakAudioVoices ?? '—'} (cap 24)`);
  push(`- ${assets.note}`);
} else {
  push(missing('asset-audit.json'));
}
push();

push('## Restart integrity');
push();
if (Array.isArray(restarts)) {
  push('| # | Restart ms | Workers | Particles | Voices |');
  push('| - | ---------- | ------- | --------- | ------ |');
  for (const r of restarts) {
    push(`| ${r.restart} | ${r.restartMs} | ${r.workers} | ${r.particles} | ${r.voices} |`);
  }
} else {
  push(missing('restarts.json'));
}
if (focus) {
  push();
  push(
    `Game seconds advanced while the tab reported itself hidden for 4 s: **${n(focus.advanced, 2)} s**  (\`focus-loss.json\`).`,
  );
}
push();

writeFileSync(join(DIR, 'summary.md'), `${lines.join('\n')}\n`);
console.log(`[report] wrote ${join(DIR, 'summary.md')} (${lines.length} lines)`);
